# **Introduction to Python. Day 2**

## *Dr Kirils Makarovs*

## *k.makarovs@exeter.ac.uk*

## *University of Exeter Q-Step Centre*

---

# **Welcome to Day 2!**

## **Yesterday, you got familiar with:**

+ The overall workflow of Jupyter Notebooks in Google Colab
+ The basics of Python syntax and operations with lists

## **Today, we are going to look at:**

+ How to navigate datasets - subsetting, accessing rows/columns
+ Operations with variables i.e. recoding, creating new variables

---

# **Preparing to work in Python**

In [ ]:
# Import the necessary libraries

import pandas as pd # data analysis and management library
import numpy as np # multi-dimensional arrays

---

# **Pandas. Working with dataframes in Python**

<figure>
<left>
<img src=https://miro.medium.com/max/481/1*n_ms1q5YoHAQXXUIfeADKQ.png  width="450">
</figure>

## **Loading dataframes from external sources**

This is how a typical dataset looks like:

<figure>
<left>
<img src=https://media.geeksforgeeks.org/wp-content/uploads/finallpandas.png width="550">
</figure>

**[Image source](https://www.geeksforgeeks.org/python-pandas-dataframe/)**

---

# **1. Getting to know a dataframe in Pandas**

In [ ]:
# Let's create a dataset with the following columns:

# Name of a staff
# Life satisfaction on the scale from 0 to 10
# Whether they were in the office last Tuesday
# Job type
# Their body temperature

df = pd.DataFrame(data = {'name' : ['Michael', 'Dwight', 'Jim', 'Pam', 'Erin', 'Kevin', 'Andy', 'Angela'],
                          'life_satisfaction' : [5, 9, 7, 7, 8, 5, 10, 4],
                          'tuesday' : [True, False, False, False, True, True, True, True],
                          'job' : ['manager', 'sales', 'sales', 'sales', 'receptionist', 'accounting', 'sales', 'accounting'],
                          'temperature' : [36.8, 37.1, 36.1, 36.6, 38.2, 39.1, 36.5, 36.9]
                          }
                  )

df

In [ ]:
# Some helpful commands to get to know the dataset

type(df) # object type - pandas.core.frame.DataFrame

df.shape # number of rows and columns

df.columns # column names

df.index # indeces

df.info() # summary of the variables in the dataset
# Dtype column shows what type of variable it is

# object - text input
# int64 - integers
# bool - Booleans (True/False)
# float64 - floats

df.head() # get the top 5 rows of the dataset

df.tail() # get the last 5 rows of the dataset

df.describe() # picks out only numerical variables (Dtype int64 or float64)
# and shows basic descriptive statistics

In [ ]:
# If you want all numbers to be rounded up to two decimals, run this line:

pd.set_option("display.precision", 2)


---

# **2. Subsetting dataframes via `.loc[]`  method**

| Command | Description |
| ------ | ----------- |
| `.iloc[]`   | position-based subsetting |
| `.loc[]` | label-based subsetting |

## **Using `.loc[]` to navigate a dataframe by row and column names**

In [ ]:
# In general, .loc[] follows the principle df.loc[rows_to_select, columns_to_select]
df


df.loc[:, ['name']] # select all rows and the variable of name

# When selecting columns, you can simply use: df['name'] or df[['name']]

df.loc[:, ['name', 'tuesday', 'temperature']] # selecting all rows and three variables

# Also, try:
# df[['name']]
# df[['name', 'tuesday', 'temperature']]

df.drop(['name'], axis = 1) # keep all variables except name.
# axis = 1 means that .drop() method will look for 'name' among column names
# axis = 0 would imply search among row names

---

# **3. Subsetting dataframes based on the values of variables**

In [ ]:
# Let's get the dataset

df

In [ ]:
# Subsetting based on the values of the variables 
# involves working with .loc[] method and using logical statements

# Say we need to select only those people who work in sales
# This is the same as saying that we need to keep all columns
# and select only those rows (people) who have 'sales' in job variable

# First, try running this:

df['job'] == 'sales'

# Each row of the dataset is tested whether its value of job variable is equal to 'sales'
# As a result, you get a Series of True or False values, and it's length is equal
# to the number of rows in the dataset

# Now if you plug this into .loc[] method, you will be able to select
# only those rows, that got True value i.e. they work in sales

df.loc[df['job'] == 'sales' , :] # select only those who work in sales and keep all columns

# Shortcuts:
# df.loc[df['job'] == 'sales']
# df[df['job'] == 'sales']

In [ ]:
# You can test more than one condition at the same time, but then each one of them
# should be put in round brackets and concatenated either with & or |

# & in Pandas means AND
# | in Pandas means OR (see image below)

# So, say we want to keep only those people who work in sales
# AND whose level of life satisfaction is above 5

df

# Here is how you can test these two condition

(df['job'] == 'sales') & (df['life_satisfaction'] > 5)

# And this is how you use them with .loc[]

df.loc[(df['job'] == 'sales') & (df['life_satisfaction'] > 5), :]

# Selecting those who are either manager or accountant

df.loc[(df['job'] == 'manager') | (df['job'] == 'accounting'), :]

<figure>
<left>
<img src=https://www.lotame.com/wp-content/uploads/2016/07/BooleanLogic_NR.jpg  width="500">
</figure>

In [ ]:
# You can use .isin() method instead of multiple OR conditions if you want to select more than one category from a single variable

# Same as a last example above, but via .isin() method

df.loc[df['job'].isin(['manager', 'accounting'])]

# Shorter:
# df[df['job'].isin(['manager', 'accounting'])]

In [ ]:
# You can filter out boolean variables - those that get only True or False values - in the following way:

# Keep only those people that have True in tuesday variable

# This is the most explicit option:

df.loc[df['tuesday'] == True, : ]

# These options also work:
# df[df['tuesday'] == True]
# df[df['tuesday']]

# If you want to keep those who have False in a boolean variable:

df.loc[df['tuesday'] != True] # same as '== False'

# This also works:
# df[df['tuesday'] != True]

## **Exercise**

Alright, time to practice!

*Please select the following subsets of the `df` dataframe:*

> 0. all rows and the columns of `job` and `temperature`
> 1. people, whose `temperature` is below or equal to 36.6
> 2. people, who **do not** work in sales
> 3. people, whose life satisfaction is **above 7** 
> 4. people, whose life satisfaction is above 7 **or** who were in on Tuesday
> 5. people, whose life satisfaction is above the mean
> 6. Michael, Jim, and Pam, and keep only `life_satisfaction` and `temperature` variables

*(Feel free to create a new code cell per each task so you could clearly see the output dataset)*

In [ ]:
df

In [ ]:
# 0. Select all rows and the columns of job and temperature

In [ ]:
# 1. People, whose temperature is below or equal 36.6

In [ ]:
# 2. People, who do not work in sales

In [ ]:
# 3.People, whose life satisfaction is above 7

In [ ]:
# 4 People, whose life satisfaction is above 7 OR who were in on Tuesday

In [ ]:
# 5. People, whose temperature is above the mean

In [ ]:
# 6. Michael, Jim, and Pam, and keep only life_satisfaction and temperature variables

---

# **6. Creating new variables in a dataframe**

## **Adding new variables manually**

In [ ]:
# When creating a new variable, the dataframe is automatically updated

df['random_column'] = 'random_value'

df['true_or_false'] = True

df['id_number'] = np.arange(start = 1, stop = 9, step = 1) # 1, 2, 3, 4, 5, 6, 7, 8

df

# Drop useless variables

df.drop(['random_column', 'true_or_false', 'id_number'], axis = 1, inplace = True)

# axis = 1 means searching for these names in column names (axis = 0 would search in row names)

# Note the inplace = True argument
# Its default value is False
# If False, return a copy. Otherwise, do operation inplace and return None.

# 'inplace' argument applies to many of the pandas methods and functions, so keep an eye on the documentation!

## **Creating new variables based on the values of existing variables**

In [ ]:
# Let me add two new variables called income_year_1, and income_year_2

# Derive 8 random values from the normal distribution which has a mean value of 35000 and sd of 10000,
# and then round up the values up to 1 decimal

df['income_year_1'] = np.random.normal(35000, 10000, 8).round(1)

df['income_year_2'] = np.random.normal(35000, 10000, 8).round(1)

df

In [ ]:
# Variable of total income

df['total_income'] = df['income_year_1'] + df['income_year_2']

# Less manual way
# df['total_income_2'] = df[['income_year_1', 'income_year_2']].sum(axis = 1)

# Variable of mean income

df['mean_income'] = df[['income_year_1', 'income_year_2']].mean(axis = 1)

df

### **Using `np.where()` to test a single if-else condition**

`np.where()` has the following structure: *`(logical condition, value of True, value if False)`*

In [ ]:
df

In [ ]:
# Creating a new variable called 'sales' that will have True for everyone who works in sales,
# and False for others

df['sales'] = np.where(df['job'] == 'sales', True, False)

# Creating a new variable called 'life_satisfaction_binary' that will have 'High LS' value
# for everyone whose LS is above or equals 5, and 'Low LS' for others

df['ls_binary'] = np.where(df['life_satisfaction'] >= 5, 'High LS', 'Low LS')

# Creating a new variable called 'satisfied_and_healthy' that will have True value
# for everyone who's got LS value higher than the mean office value AND whose body temperature is strictly 36.6

df['satisfied_and_healthy'] = np.where((df['life_satisfaction'] > df['life_satisfaction'].mean()) & (df['temperature'] == 36.6), True, False)

# Creating a new variable called 'is_rich' that will have 'YES' value
# for everyone whose total income is above the average total income in the office, and missing value for all others

df['is_rich'] = np.where(df['total_income'] > df['total_income'].mean(), 'YES', 'NO')

df

## **Exercise**

Time to practice!

*Please create the following variables in the `df` dataframe:*

> 1. `need_hospital`, that gets the value `True` if `temperature` is above 38, and `False` for others
> 2. `income_comparison`, that gets the value `'Year 1'` if income in the first year is higher than in the second year, and the value `'Year 2'` if the opposite
> 3. `status`, that gets the value `'Boss'` if it's Michael, and `'Employee'` for the rest of the people
> 4. `happy_people`, that gets the value `'super happy'` if it's Michael or anyone else with life satisfaction of 9 or 10, and `'not really'` for all others


*(Feel free to create a new code cell per each task so you could clearly see the output dataset)*

In [ ]:
# 1. `need_hospital`, that gets the value `True` if `temperature` is above 38, and `False` for others

In [ ]:
# 2. `income_comparison`, that gets the value 'Year 1' if income in the first year is higher than in the second year,
# and the value 'Year 2' if the opposite

In [ ]:
# 3. `status`, that get the value `'Boss'` if it's Michael,
# and `'Employee'` for the rest of the people

In [ ]:
# 4. `happy_people`, that gets the value `'super happy'` if it's Michael or anyone else with life satisfaction of 9 or 10,
# and `'not really'` for all others

# **That's the end of Day 2!**